# Generated by Django 6.0.5 on 2026-05-13 01:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_id', models.CharField(editable=False, max_length=30, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed')], max_length=10)),
                ('remarks', models.TextField(blank=True, default='')),
                ('failure_reason', models.CharField(blank=True, default='', max_length=255)),
                ('sender_balance_before', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('sender_balance_after', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('receiver_balance_before', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('receiver_balance_after', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_transactions', to='banking.bankaccount')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_transactions', to=settings.AUTH_USER_MODEL)),
                ('sender_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_transactions', to='banking.bankaccount')),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sender', '-created_at'], name='transaction_sender__2a81a8_idx'), models.Index(fields=['reference_id'], name='transaction_referen_897c8a_idx')],
            },
        ),
    ]
